# docker-compose.yml

services:
  mysql:
    # ★★★ 安定版のイメージを指定することを強く推奨します ★★★
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sakila
      MYSQL_USER: myappuser
      MYSQL_PASSWORD: myapppassword
      TZ: "Asia/Tokyo"

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      # ★★★ ここを追加: logsディレクトリをコンテナの/var/log/mysqlにマウント ★★★
      - ./logs:/var/log/mysql

    ports:
      - "3306:3306"

    command:
      - --general-log=1
      - --log-output=FILE
      # ★★★ ここを追加: ログファイルのパスを明示的に指定 ★★★
      - --general-log-file=/var/log/mysql/general.log
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
